class Autogenerated {
  int? id;
  String? empFirstName;
  String? empLastName;
  String? empGender;
  String? empDateOfBirth;
  String? empDateOfJoining;
  String? empPhoneNumber;
  String? empEmailId;
  String? empHomeAddrLine1;
  String? empHomeAddrLine2;
  String? empHomeAddrStreet;
  String? empHomeAddrDistrict;
  String? empHomeAddrState;
  String? empHomeAddrCountry;
  String? empHomeAddrPinCode;

  Autogenerated(
      {
      this.id,
      this.empFirstName,
      this.empLastName,
      this.empGender,
      this.empDateOfBirth,
      this.empDateOfJoining,
      this.empPhoneNumber,
      this.empEmailId,
      this.empHomeAddrLine1,
      this.empHomeAddrLine2,
      this.empHomeAddrStreet,
      this.empHomeAddrDistrict,
      this.empHomeAddrState,
      this.empHomeAddrCountry,
      this.empHomeAddrPinCode
      }
      );

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    empFirstName = json['empFirstName'];
    empLastName = json['empLastName'];
    empGender = json['empGender'];
    empDateOfBirth = json['empDateOfBirth'];
    empDateOfJoining = json['empDateOfJoining'];
    empPhoneNumber = json['empPhoneNumber'];
    empEmailId = json['empEmailId'];
    empHomeAddrLine1 = json['empHomeAddrLine1'];
    empHomeAddrLine2 = json['empHomeAddrLine2'];
    empHomeAddrStreet = json['empHomeAddrStreet'];
    empHomeAddrDistrict = json['empHomeAddrDistrict'];
    empHomeAddrState = json['empHomeAddrState'];
    empHomeAddrCountry = json['empHomeAddrCountry'];
    empHomeAddrPinCode = json['empHomeAddrPinCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['id'] = this.id;
    data['empFirstName'] = this.empFirstName;
    data['empLastName'] = this.empLastName;
    data['empGender'] = this.empGender;
    data['empDateOfBirth'] = this.empDateOfBirth;
    data['empDateOfJoining'] = this.empDateOfJoining;
    data['empPhoneNumber'] = this.empPhoneNumber;
    data['empEmailId'] = this.empEmailId;
    data['empHomeAddrLine1'] = this.empHomeAddrLine1;
    data['empHomeAddrLine2'] = this.empHomeAddrLine2;
    data['empHomeAddrStreet'] = this.empHomeAddrStreet;
    data['empHomeAddrDistrict'] = this.empHomeAddrDistrict;
    data['empHomeAddrState'] = this.empHomeAddrState;
    data['empHomeAddrCountry'] = this.empHomeAddrCountry;
    data['empHomeAddrPinCode'] = this.empHomeAddrPinCode;
    print(data);
    return data;
  }
}
